### ISSUE TITLE
Fieldname changes in Room_info

### ISSUE THREAD

**Issue by salincakli** [jwdeveloper/TikTokLiveRust#12]
Hello, 
today I could not connect to a stream. It sees an error in unwrap() at room_info.
Tiktok changed the field from "HD1" into "FULL_HD1"

https://github.com/jwdeveloper/TikTokLiveRust/blob/57e48365fa2c02df32e7a7d2a82c54423ab2b582/src/data/live_common.rs#L762

Greetings!

**Comment by ZmoleCristian** [comment]
On to it!

**Comment by ZmoleCristian** [comment]
> Hello, today I could not connect to a stream. It sees an error in unwrap() at room_info. Tiktok changed the field from "HD1" into "FULL_HD1"
> 
> https://github.com/jwdeveloper/TikTokLiveRust/blob/57e48365fa2c02df32e7a7d2a82c54423ab2b582/src/data/live_common.rs#L762
> 
> Greetings!

Can you provide a cli output? 
Did you get that using the example in readme?

**Comment by jwdeveloper** [comment]
The Library generates this Struct from proto file. So you should change that inside .proto

**Comment by salincakli** [comment]
[2024-06-12T16:47:20Z INFO  tiktoklive::core::live_client] TikTokLive: CONNECTED
thread 'tokio-runtime-worker' panicked at src\main.rs:62:75:
called `Result::unwrap()` on an `Err` value: Error("missing field `combine`", line: 1, column: 26317)

Yes I use the example and it throws the error in the OnConnected Eventhandler. This time it couldn't find the field 'combine'

**Comment by ZmoleCristian** [comment]
> [2024-06-12T16:47:20Z INFO tiktoklive::core::live_client] TikTokLive: CONNECTED thread 'tokio-runtime-worker' panicked at src\main.rs:62:75: called `Result::unwrap()` on an `Err` value: Error("missing field `combine`", line: 1, column: 26317)
> 
> Yes I use the example and it throws the error in the OnConnected Eventhandler. This time it couldn't find the field 'combine'

Yes, since the original claim:
 > Tiktok changed the field from "HD1" into "FULL_HD1"
 
 is not quite accurate, i will find a better solution to this issue so that i won't just push a sloppy patch
 you can just remove the _experimental_  feature from main until then, since the unwrap won't happen in the lib only in the binary.

**Comment by salincakli** [comment]
Thank you

**Comment by salincakli** [comment]
Fields are now optionable
