### ISSUE TITLE
get all users currently inside the live, instead of just the top viewers

### ISSUE THREAD

**Issue by bensh90** [jwdeveloper/TikTokLiveRust#16]
more a question then an issue:

is it possible to get all users currently inside the live, instead of just the top viewers?

the roomUser event currently only gives the total count, and an array of topViewers.
I want to get a list of all viewers to do some statistics on how long a user stayed after joining. But for that 
I need a list of all the users as there is a big discrepancy between top viewers and all viewers.

in one live there were 16 top viewers bis over 100 viewers.

**Comment by ZmoleCristian** [comment]
Unfortunately the roomUserSeq  does not send stats often (check #15) and from my knowledge there is no method to get all users. 
I will look into it since i also need such a stat.

**Comment by frankvHoof93** [comment]
@ZmoleCristian There isn't a way to get "All users".
I did just check the webpage, and when you click the button "Top Viewers" above the chat, it shows a list of the top 100? viewers.
Checking Network-tab in dev-menu, this seems to be doing a call to https://webcast.tiktok.com/webcast/ranklist/online_audience/ (though I'm not sure we're able to access this without signed tokens etc.)

**Comment by bensh90** [comment]
I assumed as much, but this is a bit of a bummer :\ the only alternative for me, would be to compare timestamps from when a user joined, to the time he last commented something. But not every user is actively commenting inside a live. But if there is nothing that could be done that's just how it is.

Thanks so much for looking into it anyway
