### ISSUE TITLE
How to use disconnect function?

### ISSUE THREAD

**Issue by rakhvalov** [jwdeveloper/TikTokLiveRust#22]
Hi There! I am still new to Rust and couldn't figure out how to use the function to disconnect from TikTok.

My function here:
```
pub async fn connect(username: String, mut cancel_rx: oneshot::Receiver<()>) {
    let join_handle = tokio::spawn(async move {
        let client = TikTokLive::new_client(&username)
            .configure(configure)
            .on_event(handle_event)
            .build();

        tokio::select! {
            result = client.connect() => {
                match result {
                    Ok(_) => {
                        println!("Connected to the stream - {}", username.clone());
                    },
                    Err(e) => {
                        println!("Error {}: {}", username, e);
                    }
                }
            },
        }
    });

    if let Err(e) = join_handle.await {
        eprintln!("Error while stopping the Twitch service: {:?}", e);
    }
}
```

**Comment by ZmoleCristian** [comment]
Well, it really depends on the context
When your condition to disconnect is met you can use 
```rust
client.disconnect();
```

**Comment by rakhvalov** [comment]
> Well, it really depends on the context When your condition to disconnect is met you can use
> 
> ```rust
> client.disconnect();
> ```

The problem is that I can't use the disconnect method because the variable client is already in use and the TiktokLiveClient struct doesn't implement the Copy property.

**Comment by ZmoleCristian** [comment]
I can't really tell from that snippet, if you can make a mock of your app and push it on git, i will clone it and might be able to help you.

> > Well, it really depends on the context When your condition to disconnect is met you can use
> > ```rust
> > client.disconnect();
> > ```
> 
> The problem is that I can't use the disconnect method because the variable client is already in use and the TiktokLiveClient struct doesn't implement the Copy property.

**Comment by rakhvalov** [comment]
> I can't really tell from that snippet, if you can make a mock of your app and push it on git, i will clone it and might be able to help you.
> 
> > > Well, it really depends on the context When your condition to disconnect is met you can use
> > > ```rust
> > > client.disconnect();
> > > ```
> > 
> > 
> > The problem is that I can't use the disconnect method because the variable client is already in use and the TiktokLiveClient struct doesn't implement the Copy property.

I invited you to my repository

**Comment by ZmoleCristian** [comment]
Ok, we'll continue from there
